[project]
name = "NyapixClient"
version = "0.1.0"
description = "Nyapix CLI client"
authors = [
    {name = "Nyaniko~",email = "carotte317@gmail.com"},
]
dependencies = ["requests>=2.34.2", "pydantic>=2.13.4"]
requires-python = ">=3.14"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
