services:
  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./DB/data:/var/lib/postgresql/data
      - ./DB/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file: ".env"

  client_web:
    build: ./Front/
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - .env:/app/.env
    depends_on:
      - server